//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legarage.Views.CP.App_LocalResources.CP", typeof(CP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add garage.
        /// </summary>
        public static string AddGarage {
            get {
                return ResourceManager.GetString("AddGarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add image.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add the Brand logo.
        /// </summary>
        public static string AddImageBrand {
            get {
                return ResourceManager.GetString("AddImageBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new city.
        /// </summary>
        public static string AddNewCity {
            get {
                return ResourceManager.GetString("AddNewCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new country.
        /// </summary>
        public static string AddNewCountry {
            get {
                return ResourceManager.GetString("AddNewCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new model.
        /// </summary>
        public static string AddNewModel {
            get {
                return ResourceManager.GetString("AddNewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new service.
        /// </summary>
        public static string AddNewService {
            get {
                return ResourceManager.GetString("AddNewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new vehicle.
        /// </summary>
        public static string AddNewVehicle {
            get {
                return ResourceManager.GetString("AddNewVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new vehicle .
        /// </summary>
        public static string AddNewVehicles {
            get {
                return ResourceManager.GetString("AddNewVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add rent office.
        /// </summary>
        public static string AddRentOffice {
            get {
                return ResourceManager.GetString("AddRentOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete it?.
        /// </summary>
        public static string AreSureDelete {
            get {
                return ResourceManager.GetString("AreSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Website.
        /// </summary>
        public static string Back_To_Website {
            get {
                return ResourceManager.GetString("Back_To_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand details.
        /// </summary>
        public static string BrandDetail {
            get {
                return ResourceManager.GetString("BrandDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying and Selling Vehicles.
        /// </summary>
        public static string BuyAndSellVehicles {
            get {
                return ResourceManager.GetString("BuyAndSellVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carage Images.
        /// </summary>
        public static string CarageImg {
            get {
                return ResourceManager.GetString("CarageImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carages.
        /// </summary>
        public static string Carages {
            get {
                return ResourceManager.GetString("Carages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choses.
        /// </summary>
        public static string Chose {
            get {
                return ResourceManager.GetString("Chose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City details.
        /// </summary>
        public static string CityDetails {
            get {
                return ResourceManager.GetString("CityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edite city.
        /// </summary>
        public static string CityEdit {
            get {
                return ResourceManager.GetString("CityEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose.
        /// </summary>
        public static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country details.
        /// </summary>
        public static string CountryDetails {
            get {
                return ResourceManager.GetString("CountryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string cp {
            get {
                return ResourceManager.GetString("cp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel Garages.
        /// </summary>
        public static string cp_garages {
            get {
                return ResourceManager.GetString("cp_garages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrption.
        /// </summary>
        public static string Descrption {
            get {
                return ResourceManager.GetString("Descrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        public static string Diesel {
            get {
                return ResourceManager.GetString("Diesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit brand.
        /// </summary>
        public static string EditBrand {
            get {
                return ResourceManager.GetString("EditBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit country.
        /// </summary>
        public static string EditCountry {
            get {
                return ResourceManager.GetString("EditCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited.
        /// </summary>
        public static string Edited {
            get {
                return ResourceManager.GetString("Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter image to change the image.
        /// </summary>
        public static string EditImage {
            get {
                return ResourceManager.GetString("EditImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit model.
        /// </summary>
        public static string EditModel {
            get {
                return ResourceManager.GetString("EditModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit service.
        /// </summary>
        public static string EditService {
            get {
                return ResourceManager.GetString("EditService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine size.
        /// </summary>
        public static string EngineSize {
            get {
                return ResourceManager.GetString("EngineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address please.
        /// </summary>
        public static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the brand please.
        /// </summary>
        public static string EnterBrand {
            get {
                return ResourceManager.GetString("EnterBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter city name please.
        /// </summary>
        public static string EnterCity {
            get {
                return ResourceManager.GetString("EnterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter country code please.
        /// </summary>
        public static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Color.
        /// </summary>
        public static string EnterColor {
            get {
                return ResourceManager.GetString("EnterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter country name please.
        /// </summary>
        public static string EnterCountry {
            get {
                return ResourceManager.GetString("EnterCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter descrption please.
        /// </summary>
        public static string EnterDescrption {
            get {
                return ResourceManager.GetString("EnterDescrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Driver Name.
        /// </summary>
        public static string EnterDriverName {
            get {
                return ResourceManager.GetString("EnterDriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Driver Phone.
        /// </summary>
        public static string EnterDriverPhone {
            get {
                return ResourceManager.GetString("EnterDriverPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email address please.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Engine Size.
        /// </summary>
        public static string EnterEngineSize {
            get {
                return ResourceManager.GetString("EnterEngineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterFacebook.
        /// </summary>
        public static string EnterFacebook {
            get {
                return ResourceManager.GetString("EnterFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your fax number.
        /// </summary>
        public static string EnterFax {
            get {
                return ResourceManager.GetString("EnterFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Fuel Type.
        /// </summary>
        public static string EnterFuelType {
            get {
                return ResourceManager.GetString("EnterFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter full name please.
        /// </summary>
        public static string EnterFullName {
            get {
                return ResourceManager.GetString("EnterFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Gear Box.
        /// </summary>
        public static string EnterGearBox {
            get {
                return ResourceManager.GetString("EnterGearBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter image please.
        /// </summary>
        public static string EnterImage {
            get {
                return ResourceManager.GetString("EnterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterInstagram.
        /// </summary>
        public static string EnterInstagram {
            get {
                return ResourceManager.GetString("EnterInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Is New.
        /// </summary>
        public static string EnterIsNew {
            get {
                return ResourceManager.GetString("EnterIsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Keywords.
        /// </summary>
        public static string EnterKeywords {
            get {
                return ResourceManager.GetString("EnterKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterLinkedin.
        /// </summary>
        public static string EnterLinkedin {
            get {
                return ResourceManager.GetString("EnterLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Mieage.
        /// </summary>
        public static string EnterMieage {
            get {
                return ResourceManager.GetString("EnterMieage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the model please.
        /// </summary>
        public static string EnterModel {
            get {
                return ResourceManager.GetString("EnterModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the name please.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name of owner please.
        /// </summary>
        public static string EnterOwnerName {
            get {
                return ResourceManager.GetString("EnterOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password please.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number please.
        /// </summary>
        public static string EnterPhone {
            get {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter price please.
        /// </summary>
        public static string EnterPrice {
            get {
                return ResourceManager.GetString("EnterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Quantity.
        /// </summary>
        public static string EnterQuantity {
            get {
                return ResourceManager.GetString("EnterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the service please.
        /// </summary>
        public static string EnterSerives {
            get {
                return ResourceManager.GetString("EnterSerives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterSnapchat.
        /// </summary>
        public static string EnterSnapchat {
            get {
                return ResourceManager.GetString("EnterSnapchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterTiktok.
        /// </summary>
        public static string EnterTiktok {
            get {
                return ResourceManager.GetString("EnterTiktok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Title.
        /// </summary>
        public static string EnterTitle {
            get {
                return ResourceManager.GetString("EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterTwitter.
        /// </summary>
        public static string EnterTwitter {
            get {
                return ResourceManager.GetString("EnterTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the user please.
        /// </summary>
        public static string EnterUser {
            get {
                return ResourceManager.GetString("EnterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the vehicle type please.
        /// </summary>
        public static string EnterVehicle {
            get {
                return ResourceManager.GetString("EnterVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Vehicle Sizes.
        /// </summary>
        public static string EnterVehicleSizes {
            get {
                return ResourceManager.GetString("EnterVehicleSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your whatsapp number.
        /// </summary>
        public static string EnterWhatsapp {
            get {
                return ResourceManager.GetString("EnterWhatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Year.
        /// </summary>
        public static string EnterYear {
            get {
                return ResourceManager.GetString("EnterYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterYoutube.
        /// </summary>
        public static string EnterYoutube {
            get {
                return ResourceManager.GetString("EnterYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel type.
        /// </summary>
        public static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Full_Name {
            get {
                return ResourceManager.GetString("Full Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage Contact Information:.
        /// </summary>
        public static string GarageContactInformation {
            get {
                return ResourceManager.GetString("GarageContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage detail.
        /// </summary>
        public static string GarageDetail {
            get {
                return ResourceManager.GetString("GarageDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit garage.
        /// </summary>
        public static string GarageEdit {
            get {
                return ResourceManager.GetString("GarageEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage name.
        /// </summary>
        public static string GarageName {
            get {
                return ResourceManager.GetString("GarageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garages.
        /// </summary>
        public static string Garages {
            get {
                return ResourceManager.GetString("Garages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearbox.
        /// </summary>
        public static string Gearbox {
            get {
                return ResourceManager.GetString("Gearbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your instagram.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there market.
        /// </summary>
        public static string IsMarket {
            get {
                return ResourceManager.GetString("IsMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is new.
        /// </summary>
        public static string IsNew {
            get {
                return ResourceManager.GetString("IsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 100 thousand km.
        /// </summary>
        public static string Less100 {
            get {
                return ResourceManager.GetString("Less100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 150 thousand km.
        /// </summary>
        public static string Less150 {
            get {
                return ResourceManager.GetString("Less150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 50 thousand km.
        /// </summary>
        public static string Less50 {
            get {
                return ResourceManager.GetString("Less50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your linkedin.
        /// </summary>
        public static string Linkedin {
            get {
                return ResourceManager.GetString("Linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main services.
        /// </summary>
        public static string MainServices {
            get {
                return ResourceManager.GetString("MainServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mieage.
        /// </summary>
        public static string Mieage {
            get {
                return ResourceManager.GetString("Mieage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Id.
        /// </summary>
        public static string Model_id {
            get {
                return ResourceManager.GetString("Model_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string Models {
            get {
                return ResourceManager.GetString("Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modle detail.
        /// </summary>
        public static string ModleDetail {
            get {
                return ResourceManager.GetString("ModleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 150 thousand km.
        /// </summary>
        public static string More150 {
            get {
                return ResourceManager.GetString("More150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of carage.
        /// </summary>
        public static string NameOfCarage {
            get {
                return ResourceManager.GetString("NameOfCarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of part.
        /// </summary>
        public static string NameOfPart {
            get {
                return ResourceManager.GetString("NameOfPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of rent office.
        /// </summary>
        public static string NameOfRentOffice {
            get {
                return ResourceManager.GetString("NameOfRentOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string nav_services {
            get {
                return ResourceManager.GetString("nav_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No brands avalible.
        /// </summary>
        public static string NoBrand {
            get {
                return ResourceManager.GetString("NoBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Cities avalible.
        /// </summary>
        public static string NoCity {
            get {
                return ResourceManager.GetString("NoCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No country avalible.
        /// </summary>
        public static string NoCountry {
            get {
                return ResourceManager.GetString("NoCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error in sql query.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No garages avalible.
        /// </summary>
        public static string NoGarages {
            get {
                return ResourceManager.GetString("NoGarages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no image.
        /// </summary>
        public static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No model avalible.
        /// </summary>
        public static string NoModel {
            get {
                return ResourceManager.GetString("NoModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No offers avalible.
        /// </summary>
        public static string NoOffers {
            get {
                return ResourceManager.GetString("NoOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Parts.
        /// </summary>
        public static string NoParts {
            get {
                return ResourceManager.GetString("NoParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rent offices.
        /// </summary>
        public static string NoRentOffices {
            get {
                return ResourceManager.GetString("NoRentOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service avalible.
        /// </summary>
        public static string NoService {
            get {
                return ResourceManager.GetString("NoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user avalible.
        /// </summary>
        public static string NoUser {
            get {
                return ResourceManager.GetString("NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vehicle avalible.
        /// </summary>
        public static string NoVehicle {
            get {
                return ResourceManager.GetString("NoVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Winches.
        /// </summary>
        public static string NoWinches {
            get {
                return ResourceManager.GetString("NoWinches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old.
        /// </summary>
        public static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current image.
        /// </summary>
        public static string OldImage {
            get {
                return ResourceManager.GetString("OldImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string Paymentmethod {
            get {
                return ResourceManager.GetString("Paymentmethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol.
        /// </summary>
        public static string Petrol {
            get {
                return ResourceManager.GetString("Petrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products or Parts.
        /// </summary>
        public static string ProductsOrParts {
            get {
                return ResourceManager.GetString("ProductsOrParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Winches.
        /// </summary>
        public static string RecoveryWinches {
            get {
                return ResourceManager.GetString("RecoveryWinches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent office details.
        /// </summary>
        public static string RentOfficeDetails {
            get {
                return ResourceManager.GetString("RentOfficeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent office edit.
        /// </summary>
        public static string RentOfficeEdit {
            get {
                return ResourceManager.GetString("RentOfficeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent offices.
        /// </summary>
        public static string RentOffices {
            get {
                return ResourceManager.GetString("RentOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the county please.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service details.
        /// </summary>
        public static string ServiceDetail {
            get {
                return ResourceManager.GetString("ServiceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        public static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your snapchat.
        /// </summary>
        public static string Snapchat {
            get {
                return ResourceManager.GetString("Snapchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Id.
        /// </summary>
        public static string Store_id {
            get {
                return ResourceManager.GetString("Store_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main sections.
        /// </summary>
        public static string TheMainSections {
            get {
                return ResourceManager.GetString("TheMainSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your tiktok.
        /// </summary>
        public static string Tiktok {
            get {
                return ResourceManager.GetString("Tiktok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of part.
        /// </summary>
        public static string TypeOfPart {
            get {
                return ResourceManager.GetString("TypeOfPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload garage image.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user name please.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user details.
        /// </summary>
        public static string UserEdit {
            get {
                return ResourceManager.GetString("UserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User image.
        /// </summary>
        public static string UserImg {
            get {
                return ResourceManager.GetString("UserImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle detail.
        /// </summary>
        public static string VehicleDetail {
            get {
                return ResourceManager.GetString("VehicleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle edit type.
        /// </summary>
        public static string VehicleEdit {
            get {
                return ResourceManager.GetString("VehicleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle type.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle types.
        /// </summary>
        public static string VehicleTypes {
            get {
                return ResourceManager.GetString("VehicleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp.
        /// </summary>
        public static string Whatsapp {
            get {
                return ResourceManager.GetString("Whatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp number.
        /// </summary>
        public static string WhatsappNumber {
            get {
                return ResourceManager.GetString("WhatsappNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your unique user name.
        /// </summary>
        public static string WhatUserName {
            get {
                return ResourceManager.GetString("WhatUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your youtube.
        /// </summary>
        public static string Youtube {
            get {
                return ResourceManager.GetString("Youtube", resourceCulture);
            }
        }
    }
}
