//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Users {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Users() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legarage.Views.Users.App_LocalResources.Users", typeof(Users).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agreement.
        /// </summary>
        public static string agreement {
            get {
                return ResourceManager.GetString("agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlreadyRegistered.
        /// </summary>
        public static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string chng_password {
            get {
                return ResourceManager.GetString("chng_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code_sent.
        /// </summary>
        public static string code_sent {
            get {
                return ResourceManager.GetString("code_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm new password.
        /// </summary>
        public static string confirmnewpassword {
            get {
                return ResourceManager.GetString("confirmnewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter confirm code.
        /// </summary>
        public static string enter_conf_code {
            get {
                return ResourceManager.GetString("enter_conf_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        public static string Enternewpassword {
            get {
                return ResourceManager.GetString("Enternewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Number.
        /// </summary>
        public static string FaxNumber {
            get {
                return ResourceManager.GetString("FaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Email address is required..
        /// </summary>
        public static string invalid_feedback {
            get {
                return ResourceManager.GetString("invalid_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid first name is required..
        /// </summary>
        public static string invalid_feedback1 {
            get {
                return ResourceManager.GetString("invalid_feedback1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid last name is required..
        /// </summary>
        public static string invalid_feedback2 {
            get {
                return ResourceManager.GetString("invalid_feedback2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid first name is required.
        /// </summary>
        public static string invalid_feedback3 {
            get {
                return ResourceManager.GetString("invalid_feedback3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid last name is required..
        /// </summary>
        public static string invalid_feedback4 {
            get {
                return ResourceManager.GetString("invalid_feedback4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can reset your password here..
        /// </summary>
        public static string Label1 {
            get {
                return ResourceManager.GetString("Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we have send confrim code.
        /// </summary>
        public static string Label2 {
            get {
                return ResourceManager.GetString("Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address or Phone number.
        /// </summary>
        public static string Label3 {
            get {
                return ResourceManager.GetString("Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can reset your password here..
        /// </summary>
        public static string lbl_chng_password {
            get {
                return ResourceManager.GetString("lbl_chng_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New around here?.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new password.
        /// </summary>
        public static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to old password.
        /// </summary>
        public static string oldPassword {
            get {
                return ResourceManager.GetString("oldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        public static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Request.
        /// </summary>
        public static string PasswordResetRequest {
            get {
                return ResourceManager.GetString("PasswordResetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Details.
        /// </summary>
        public static string ProfileDetails {
            get {
                return ResourceManager.GetString("ProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residance Address.
        /// </summary>
        public static string ResidanceAddress {
            get {
                return ResourceManager.GetString("ResidanceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send My Password.
        /// </summary>
        public static string SendMyPassword {
            get {
                return ResourceManager.GetString("SendMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then.
        /// </summary>
        public static string Then {
            get {
                return ResourceManager.GetString("Then", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Profile Image.
        /// </summary>
        public static string UploadProfileImage {
            get {
                return ResourceManager.GetString("UploadProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is incorrect.
        /// </summary>
        public static string UsernameIncorrect {
            get {
                return ResourceManager.GetString("UsernameIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 character password.
        /// </summary>
        public static string valid_character {
            get {
                return ResourceManager.GetString("valid_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid confirm password.
        /// </summary>
        public static string valid_conf_pass {
            get {
                return ResourceManager.GetString("valid_conf_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valid_email.
        /// </summary>
        public static string valid_email {
            get {
                return ResourceManager.GetString("valid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valid_pass_confpass.
        /// </summary>
        public static string valid_pass_confpass {
            get {
                return ResourceManager.GetString("valid_pass_confpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid password.
        /// </summary>
        public static string valid_password {
            get {
                return ResourceManager.GetString("valid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website and/or Social Media.
        /// </summary>
        public static string WebsiteSocialMedia {
            get {
                return ResourceManager.GetString("WebsiteSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp Number.
        /// </summary>
        public static string WhatsappNumber {
            get {
                return ResourceManager.GetString("WhatsappNumber", resourceCulture);
            }
        }
    }
}
