//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class University {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal University() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGAW_ECHO.Views.CP_Universities.App_LocalResources.University", typeof(University).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Description.
        /// </summary>
        public static string arabic_description {
            get {
                return ResourceManager.GetString("arabic description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Univesity Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to english description.
        /// </summary>
        public static string english_description {
            get {
                return ResourceManager.GetString("english description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Univesity Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neighborhood.
        /// </summary>
        public static string neighborhood {
            get {
                return ResourceManager.GetString("neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new university.
        /// </summary>
        public static string new_University {
            get {
                return ResourceManager.GetString("new_University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter arabic description.
        /// </summary>
        public static string Please_enter_arabic_description {
            get {
                return ResourceManager.GetString("Please enter arabic description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter english description.
        /// </summary>
        public static string please_enter_english_description {
            get {
                return ResourceManager.GetString("please enter english description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter turkish description.
        /// </summary>
        public static string please_enter_turkish_description {
            get {
                return ResourceManager.GetString("please enter turkish description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter university name.
        /// </summary>
        public static string Please_enter_university_name {
            get {
                return ResourceManager.GetString("Please enter university name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turkish description.
        /// </summary>
        public static string turkish_description {
            get {
                return ResourceManager.GetString("turkish description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universities.
        /// </summary>
        public static string Universities {
            get {
                return ResourceManager.GetString("Universities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to university_name.
        /// </summary>
        public static string university_name {
            get {
                return ResourceManager.GetString("university_name", resourceCulture);
            }
        }
    }
}
