//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CP_Vehicles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CP_Vehicles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legarage.Views.CP_Vehicles.App_LocalResources.CP_Vehicles", typeof(CP_Vehicles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new vehicles.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle has been added.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new image.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the image  please.
        /// </summary>
        public static string AddImageP {
            get {
                return ResourceManager.GetString("AddImageP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose the country firstly.
        /// </summary>
        public static string ChoseCountryFirstly {
            get {
                return ResourceManager.GetString("ChoseCountryFirstly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the vehicle.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle has been deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the image.
        /// </summary>
        public static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The descrption.
        /// </summary>
        public static string Descrption {
            get {
                return ResourceManager.GetString("Descrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        public static string Diesel {
            get {
                return ResourceManager.GetString("Diesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the vehicle.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle has been edited.
        /// </summary>
        public static string Edited {
            get {
                return ResourceManager.GetString("Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter image to change the current image.
        /// </summary>
        public static string EditImage {
            get {
                return ResourceManager.GetString("EditImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The engine size.
        /// </summary>
        public static string EngineSize {
            get {
                return ResourceManager.GetString("EngineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address.
        /// </summary>
        public static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address please.
        /// </summary>
        public static string EnterAddressP {
            get {
                return ResourceManager.GetString("EnterAddressP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the city please.
        /// </summary>
        public static string EnterCityP {
            get {
                return ResourceManager.GetString("EnterCityP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the color.
        /// </summary>
        public static string EnterColor {
            get {
                return ResourceManager.GetString("EnterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the color please.
        /// </summary>
        public static string EnterColorP {
            get {
                return ResourceManager.GetString("EnterColorP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the descrption.
        /// </summary>
        public static string EnterDescrption {
            get {
                return ResourceManager.GetString("EnterDescrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the descrption please.
        /// </summary>
        public static string EnterDescrptionP {
            get {
                return ResourceManager.GetString("EnterDescrptionP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the engine size.
        /// </summary>
        public static string EnterEngineSize {
            get {
                return ResourceManager.GetString("EnterEngineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the engineSize please.
        /// </summary>
        public static string EnterEngineSizeP {
            get {
                return ResourceManager.GetString("EnterEngineSizeP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the fuel type.
        /// </summary>
        public static string EnterFuelType {
            get {
                return ResourceManager.GetString("EnterFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the fuel type please.
        /// </summary>
        public static string EnterFuelTypeP {
            get {
                return ResourceManager.GetString("EnterFuelTypeP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the gear box.
        /// </summary>
        public static string EnterGearbox {
            get {
                return ResourceManager.GetString("EnterGearbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the gear box please.
        /// </summary>
        public static string EnterGearBoxP {
            get {
                return ResourceManager.GetString("EnterGearBoxP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the keywords.
        /// </summary>
        public static string EnterKeywords {
            get {
                return ResourceManager.GetString("EnterKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the keywords please.
        /// </summary>
        public static string EnterKeywordsP {
            get {
                return ResourceManager.GetString("EnterKeywordsP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the mieage.
        /// </summary>
        public static string EnterMieage {
            get {
                return ResourceManager.GetString("EnterMieage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the mieage please.
        /// </summary>
        public static string EnterMieageP {
            get {
                return ResourceManager.GetString("EnterMieageP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the model please.
        /// </summary>
        public static string EnterModelP {
            get {
                return ResourceManager.GetString("EnterModelP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the owner name.
        /// </summary>
        public static string EnterOwnerName {
            get {
                return ResourceManager.GetString("EnterOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the ownerName please.
        /// </summary>
        public static string EnterOwnerNameP {
            get {
                return ResourceManager.GetString("EnterOwnerNameP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phone please.
        /// </summary>
        public static string EnterPhoneP {
            get {
                return ResourceManager.GetString("EnterPhoneP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the price.
        /// </summary>
        public static string EnterPrice {
            get {
                return ResourceManager.GetString("EnterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the price please.
        /// </summary>
        public static string EnterPriceP {
            get {
                return ResourceManager.GetString("EnterPriceP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the quantity.
        /// </summary>
        public static string EnterQuantity {
            get {
                return ResourceManager.GetString("EnterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the quantity please.
        /// </summary>
        public static string EnterQuantityP {
            get {
                return ResourceManager.GetString("EnterQuantityP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title.
        /// </summary>
        public static string EnterTitle {
            get {
                return ResourceManager.GetString("EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title please.
        /// </summary>
        public static string EnterTitleP {
            get {
                return ResourceManager.GetString("EnterTitleP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user name.
        /// </summary>
        public static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the user please.
        /// </summary>
        public static string EnterUserP {
            get {
                return ResourceManager.GetString("EnterUserP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the vehicle please.
        /// </summary>
        public static string EnterVehicleP {
            get {
                return ResourceManager.GetString("EnterVehicleP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Whatsapp number.
        /// </summary>
        public static string EnterWhatsapp {
            get {
                return ResourceManager.GetString("EnterWhatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the year.
        /// </summary>
        public static string EnterYear {
            get {
                return ResourceManager.GetString("EnterYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the year please.
        /// </summary>
        public static string EnterYearP {
            get {
                return ResourceManager.GetString("EnterYearP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fuel type.
        /// </summary>
        public static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gear box.
        /// </summary>
        public static string Gearbox {
            get {
                return ResourceManager.GetString("Gearbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle image.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is new.
        /// </summary>
        public static string IsNew {
            get {
                return ResourceManager.GetString("IsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less100.
        /// </summary>
        public static string Less100 {
            get {
                return ResourceManager.GetString("Less100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less150.
        /// </summary>
        public static string Less150 {
            get {
                return ResourceManager.GetString("Less150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less50.
        /// </summary>
        public static string Less50 {
            get {
                return ResourceManager.GetString("Less50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mieage.
        /// </summary>
        public static string Mieage {
            get {
                return ResourceManager.GetString("Mieage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More150.
        /// </summary>
        public static string More150 {
            get {
                return ResourceManager.GetString("More150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no cities avalible.
        /// </summary>
        public static string NoCity {
            get {
                return ResourceManager.GetString("NoCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no countries avalible.
        /// </summary>
        public static string NoCountry {
            get {
                return ResourceManager.GetString("NoCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no images avalible.
        /// </summary>
        public static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no models avalible.
        /// </summary>
        public static string NoModel {
            get {
                return ResourceManager.GetString("NoModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no users avalible.
        /// </summary>
        public static string NoUser {
            get {
                return ResourceManager.GetString("NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no vehicles avalible.
        /// </summary>
        public static string NoVehicle {
            get {
                return ResourceManager.GetString("NoVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old.
        /// </summary>
        public static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner name.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol.
        /// </summary>
        public static string Petrol {
            get {
                return ResourceManager.GetString("Petrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicles.
        /// </summary>
        public static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle type.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WhatsApp number.
        /// </summary>
        public static string Whatsapp {
            get {
                return ResourceManager.GetString("Whatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
