//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legarage.Views.Home.App_LocalResources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is to fully cater your vehicle needs and make you happy by custom buying and selling of any vehicles, whether it is a car, 4x4, motorcycle, truck or even bus, enjoy your browsing of the vehicles we have and have fun..
        /// </summary>
        public static string buyandsell_description {
            get {
                return ResourceManager.GetString("buyandsell_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy and Sell Now.
        /// </summary>
        public static string buyandsell_now {
            get {
                return ResourceManager.GetString("buyandsell_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy &amp; Sell.
        /// </summary>
        public static string buyandsell_tab {
            get {
                return ResourceManager.GetString("buyandsell_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy and Sell.
        /// </summary>
        public static string buyandselldiv {
            get {
                return ResourceManager.GetString("buyandselldiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact the Seller to Buy in the Product Details.
        /// </summary>
        public static string buycontactsellerindetails {
            get {
                return ResourceManager.GetString("buycontactsellerindetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Area.
        /// </summary>
        public static string CityArea {
            get {
                return ResourceManager.GetString("CityArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Company.
        /// </summary>
        public static string companyname {
            get {
                return ResourceManager.GetString("companyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactPageTitle {
            get {
                return ResourceManager.GetString("ContactPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string desecription {
            get {
                return ResourceManager.GetString("desecription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        public static string devby {
            get {
                return ResourceManager.GetString("devby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out and book the best Garages and benefit from their services and rest assured that you will be satisfied regarding your garage needs and you will be able to search for the specific thing that you need and get it fixed and assisted..
        /// </summary>
        public static string garages_description {
            get {
                return ResourceManager.GetString("garages_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string garages_location {
            get {
                return ResourceManager.GetString("garages_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string garages_mobile {
            get {
                return ResourceManager.GetString("garages_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string garages_rating {
            get {
                return ResourceManager.GetString("garages_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garages Services.
        /// </summary>
        public static string garages_services {
            get {
                return ResourceManager.GetString("garages_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        public static string garages_show {
            get {
                return ResourceManager.GetString("garages_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garages.
        /// </summary>
        public static string garages_tab {
            get {
                return ResourceManager.GetString("garages_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string garages_website {
            get {
                return ResourceManager.GetString("garages_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string index_title {
            get {
                return ResourceManager.GetString("index_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string learnmore {
            get {
                return ResourceManager.GetString("learnmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you looking for ?.
        /// </summary>
        public static string lookingfortitle {
            get {
                return ResourceManager.GetString("lookingfortitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Entries.
        /// </summary>
        public static string nav_add {
            get {
                return ResourceManager.GetString("nav_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy &amp; Sell.
        /// </summary>
        public static string nav_buyandsell {
            get {
                return ResourceManager.GetString("nav_buyandsell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garages.
        /// </summary>
        public static string nav_garages {
            get {
                return ResourceManager.GetString("nav_garages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string nav_log {
            get {
                return ResourceManager.GetString("nav_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string nav_lout {
            get {
                return ResourceManager.GetString("nav_lout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Offers.
        /// </summary>
        public static string nav_myoffers {
            get {
                return ResourceManager.GetString("nav_myoffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string nav_myprofile {
            get {
                return ResourceManager.GetString("nav_myprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string nav_offers {
            get {
                return ResourceManager.GetString("nav_offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Parts.
        /// </summary>
        public static string nav_parts {
            get {
                return ResourceManager.GetString("nav_parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        public static string nav_recovery {
            get {
                return ResourceManager.GetString("nav_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string nav_reg {
            get {
                return ResourceManager.GetString("nav_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string nav_rent {
            get {
                return ResourceManager.GetString("nav_rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string nav_search {
            get {
                return ResourceManager.GetString("nav_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string nav_services {
            get {
                return ResourceManager.GetString("nav_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Entries.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts and Products.
        /// </summary>
        public static string parts_and_products {
            get {
                return ResourceManager.GetString("parts_and_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        public static string parts_tab {
            get {
                return ResourceManager.GetString("parts_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand:.
        /// </summary>
        public static string product_brand {
            get {
                return ResourceManager.GetString("product_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string product_buy {
            get {
                return ResourceManager.GetString("product_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories:.
        /// </summary>
        public static string product_categories {
            get {
                return ResourceManager.GetString("product_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string product_location {
            get {
                return ResourceManager.GetString("product_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers:.
        /// </summary>
        public static string product_offers {
            get {
                return ResourceManager.GetString("product_offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can easily and efficiently request a Winche in your area to tow your vehicle whether car, motorbike or any other vehicle within the specifications and through this website after requesting, a Winche will come to you anywhere whether in the middle of a long high way road or in the wilderness..
        /// </summary>
        public static string recovery_description {
            get {
                return ResourceManager.GetString("recovery_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Recovery Service.
        /// </summary>
        public static string recovery_services {
            get {
                return ResourceManager.GetString("recovery_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        public static string recovery_tab {
            get {
                return ResourceManager.GetString("recovery_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Recovery.
        /// </summary>
        public static string recovery_vehicles {
            get {
                return ResourceManager.GetString("recovery_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string rent_bttn {
            get {
                return ResourceManager.GetString("rent_bttn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent a car or motorcycle or whatever suits your current needs and/or browse the list of renting offices and their for rent vehicles and checkout their information until you are fully satisfied then book the rent..
        /// </summary>
        public static string rent_description {
            get {
                return ResourceManager.GetString("rent_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Renting Services.
        /// </summary>
        public static string rent_services {
            get {
                return ResourceManager.GetString("rent_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string rent_tab {
            get {
                return ResourceManager.GetString("rent_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Rent.
        /// </summary>
        public static string rent_vehicles {
            get {
                return ResourceManager.GetString("rent_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Available Winches.
        /// </summary>
        public static string search_winches {
            get {
                return ResourceManager.GetString("search_winches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Garages.
        /// </summary>
        public static string see_garages {
            get {
                return ResourceManager.GetString("see_garages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles Sale.
        /// </summary>
        public static string vehicles_sale {
            get {
                return ResourceManager.GetString("vehicles_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Sizes.
        /// </summary>
        public static string VehicleSizes {
            get {
                return ResourceManager.GetString("VehicleSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is LeGarage where you can contact garages, rental offices, buy and sell vehicle products and parts and also recover and tow your vehicle, we are here for your vehicle needs..
        /// </summary>
        public static string websitedescription {
            get {
                return ResourceManager.GetString("websitedescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeGarage.
        /// </summary>
        public static string websitename {
            get {
                return ResourceManager.GetString("websitename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeGarage. All rights reserved..
        /// </summary>
        public static string websitenameandrights {
            get {
                return ResourceManager.GetString("websitenameandrights", resourceCulture);
            }
        }
    }
}
