//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Offers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Offers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legarage.Views.Offers.App_LocalResources.Offers", typeof(Offers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Offer.
        /// </summary>
        public static string AddOffer {
            get {
                return ResourceManager.GetString("AddOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddProduct.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added By .
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Address.
        /// </summary>
        public static string CityAddress {
            get {
                return ResourceManager.GetString("CityAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Percentage.
        /// </summary>
        public static string DiscountPercentage {
            get {
                return ResourceManager.GetString("DiscountPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter offer&apos;s new discounted price in numbers.
        /// </summary>
        public static string Enterdiscounted {
            get {
                return ResourceManager.GetString("Enterdiscounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Offer and Seller Description.
        /// </summary>
        public static string EnterOfferandSellerDescription {
            get {
                return ResourceManager.GetString("EnterOfferandSellerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Offers.
        /// </summary>
        public static string MyOfferPageTitle {
            get {
                return ResourceManager.GetString("MyOfferPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyOffers.
        /// </summary>
        public static string MyOffers {
            get {
                return ResourceManager.GetString("MyOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found for this user.
        /// </summary>
        public static string Nodata {
            get {
                return ResourceManager.GetString("Nodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Details.
        /// </summary>
        public static string OfferDetails {
            get {
                return ResourceManager.GetString("OfferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfferPrice.
        /// </summary>
        public static string OfferPrice {
            get {
                return ResourceManager.GetString("OfferPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer type.
        /// </summary>
        public static string Offertype {
            get {
                return ResourceManager.GetString("Offertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Types.
        /// </summary>
        public static string OfferTypes {
            get {
                return ResourceManager.GetString("OfferTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer User.
        /// </summary>
        public static string OfferUser {
            get {
                return ResourceManager.GetString("OfferUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldPrice.
        /// </summary>
        public static string OldPrice {
            get {
                return ResourceManager.GetString("OldPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Price.
        /// </summary>
        public static string OriginalPrice {
            get {
                return ResourceManager.GetString("OriginalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal.
        /// </summary>
        public static string Paypal {
            get {
                return ResourceManager.GetString("Paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Offer and Seller Description.
        /// </summary>
        public static string PlaceHolder_eDescription {
            get {
                return ResourceManager.GetString("PlaceHolder_eDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Offer&apos;s Full Details.
        /// </summary>
        public static string PlaceHolder_eDetails {
            get {
                return ResourceManager.GetString("PlaceHolder_eDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter offer&apos;s original price in numbers.
        /// </summary>
        public static string PlaceHolder1 {
            get {
                return ResourceManager.GetString("PlaceHolder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter offer&apos;s new discounted price in numbers.
        /// </summary>
        public static string PlaceHolder2 {
            get {
                return ResourceManager.GetString("PlaceHolder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your accepted payment methods.
        /// </summary>
        public static string PlaceHolder3 {
            get {
                return ResourceManager.GetString("PlaceHolder3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select_garages.
        /// </summary>
        public static string select_garages {
            get {
                return ResourceManager.GetString("select_garages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select winches.
        /// </summary>
        public static string select_winches {
            get {
                return ResourceManager.GetString("select winches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select brands you want .
        /// </summary>
        public static string Selectbrandsyouwant {
            get {
                return ResourceManager.GetString("Selectbrandsyouwant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Categories you want.
        /// </summary>
        public static string SelectCategoriesyouwant {
            get {
                return ResourceManager.GetString("SelectCategoriesyouwant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selectgarages.
        /// </summary>
        public static string selectgarages {
            get {
                return ResourceManager.GetString("selectgarages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Vehicle Types you want.
        /// </summary>
        public static string SelectVehicleTypesyouwant {
            get {
                return ResourceManager.GetString("SelectVehicleTypesyouwant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Winches.
        /// </summary>
        public static string SelectWinches {
            get {
                return ResourceManager.GetString("SelectWinches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SellerContactInformation.
        /// </summary>
        public static string SellerContactInformation {
            get {
                return ResourceManager.GetString("SellerContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        public static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload OfferImage.
        /// </summary>
        public static string UploadOfferImage {
            get {
                return ResourceManager.GetString("UploadOfferImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weaccept.
        /// </summary>
        public static string Weaccept {
            get {
                return ResourceManager.GetString("Weaccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp.
        /// </summary>
        public static string Whatsapp {
            get {
                return ResourceManager.GetString("Whatsapp", resourceCulture);
            }
        }
    }
}
