//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CP_Garages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CP_Garages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legarage.Views.CP_Garages.App_LocalResources.CP_Garages", typeof(CP_Garages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new garage.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The carage has been added.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Image.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The brands.
        /// </summary>
        public static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carage image.
        /// </summary>
        public static string CarageImg {
            get {
                return ResourceManager.GetString("CarageImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The carages.
        /// </summary>
        public static string Carages {
            get {
                return ResourceManager.GetString("Carages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstly chose the country.
        /// </summary>
        public static string ChoseCountry {
            get {
                return ResourceManager.GetString("ChoseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose owner name.
        /// </summary>
        public static string ChoseOwnerName {
            get {
                return ResourceManager.GetString("ChoseOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current image.
        /// </summary>
        public static string CurrentImage {
            get {
                return ResourceManager.GetString("CurrentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the carage.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The carage has been deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the image.
        /// </summary>
        public static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The descrption.
        /// </summary>
        public static string Descrption {
            get {
                return ResourceManager.GetString("Descrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carage details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the carage.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The carage has been edited.
        /// </summary>
        public static string Edited {
            get {
                return ResourceManager.GetString("Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an image change to change the current image.
        /// </summary>
        public static string EditImage {
            get {
                return ResourceManager.GetString("EditImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the location.
        /// </summary>
        public static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the location please.
        /// </summary>
        public static string EnterAddressPlease {
            get {
                return ResourceManager.GetString("EnterAddressPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the brands please.
        /// </summary>
        public static string EnterBrandPlease {
            get {
                return ResourceManager.GetString("EnterBrandPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the carage name.
        /// </summary>
        public static string EnterCarageName {
            get {
                return ResourceManager.GetString("EnterCarageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterthe city please.
        /// </summary>
        public static string EnterCityPlease {
            get {
                return ResourceManager.GetString("EnterCityPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter descrption.
        /// </summary>
        public static string EnterDescrption {
            get {
                return ResourceManager.GetString("EnterDescrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterthe descrption please.
        /// </summary>
        public static string EnterDescrptionPlease {
            get {
                return ResourceManager.GetString("EnterDescrptionPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter facebook.
        /// </summary>
        public static string EnterFacebook {
            get {
                return ResourceManager.GetString("EnterFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the fax.
        /// </summary>
        public static string EnterFax {
            get {
                return ResourceManager.GetString("EnterFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter carage image.
        /// </summary>
        public static string EnterImage {
            get {
                return ResourceManager.GetString("EnterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the carage image please.
        /// </summary>
        public static string EnterImagePlease {
            get {
                return ResourceManager.GetString("EnterImagePlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter instagram.
        /// </summary>
        public static string EnterInstagram {
            get {
                return ResourceManager.GetString("EnterInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the keywords.
        /// </summary>
        public static string EnterKeywords {
            get {
                return ResourceManager.GetString("EnterKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the keywords please.
        /// </summary>
        public static string EnterKeywordsPlease {
            get {
                return ResourceManager.GetString("EnterKeywordsPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter linkedin.
        /// </summary>
        public static string EnterLinkedin {
            get {
                return ResourceManager.GetString("EnterLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entername.
        /// </summary>
        public static string Entername {
            get {
                return ResourceManager.GetString("Entername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter carage name please.
        /// </summary>
        public static string EnterNamePlease {
            get {
                return ResourceManager.GetString("EnterNamePlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter carage owner name please.
        /// </summary>
        public static string EnterOwnerNamePlease {
            get {
                return ResourceManager.GetString("EnterOwnerNamePlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phone number.
        /// </summary>
        public static string EnterPhone {
            get {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phone number please.
        /// </summary>
        public static string EnterPhonePlease {
            get {
                return ResourceManager.GetString("EnterPhonePlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the serives please.
        /// </summary>
        public static string EnterSerivesPlease {
            get {
                return ResourceManager.GetString("EnterSerivesPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter snapchat.
        /// </summary>
        public static string EnterSnapchat {
            get {
                return ResourceManager.GetString("EnterSnapchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter tiktok.
        /// </summary>
        public static string EnterTiktok {
            get {
                return ResourceManager.GetString("EnterTiktok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter twitter.
        /// </summary>
        public static string EnterTwitter {
            get {
                return ResourceManager.GetString("EnterTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the vehicles please.
        /// </summary>
        public static string EnterVehiclePlease {
            get {
                return ResourceManager.GetString("EnterVehiclePlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter website.
        /// </summary>
        public static string EnterWebsite {
            get {
                return ResourceManager.GetString("EnterWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the WhatsApp number.
        /// </summary>
        public static string EnterWhatsapp {
            get {
                return ResourceManager.GetString("EnterWhatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterW the whatsapp number please.
        /// </summary>
        public static string EnterWhatsappPlease {
            get {
                return ResourceManager.GetString("EnterWhatsappPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter youtube.
        /// </summary>
        public static string EnterYoutube {
            get {
                return ResourceManager.GetString("EnterYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The carage images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instagram.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linkedin.
        /// </summary>
        public static string Linkedin {
            get {
                return ResourceManager.GetString("Linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of carage.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No brands avalible.
        /// </summary>
        public static string NoBrand {
            get {
                return ResourceManager.GetString("NoBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images avalible.
        /// </summary>
        public static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service avalible.
        /// </summary>
        public static string NoService {
            get {
                return ResourceManager.GetString("NoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users avalible.
        /// </summary>
        public static string NoUser {
            get {
                return ResourceManager.GetString("NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vehicle avalible.
        /// </summary>
        public static string NoVehicle {
            get {
                return ResourceManager.GetString("NoVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner name.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snapchat.
        /// </summary>
        public static string Snapchat {
            get {
                return ResourceManager.GetString("Snapchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tiktok.
        /// </summary>
        public static string Tiktok {
            get {
                return ResourceManager.GetString("Tiktok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicles.
        /// </summary>
        public static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The whatsapp.
        /// </summary>
        public static string Whatsapp {
            get {
                return ResourceManager.GetString("Whatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The youtube.
        /// </summary>
        public static string Youtube {
            get {
                return ResourceManager.GetString("Youtube", resourceCulture);
            }
        }
    }
}
