//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("learn_arabic.Resources.Languages.English.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreSure {
            get {
                return ResourceManager.GetString("AreSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You willn&apos;t be able to revert this item ! .
        /// </summary>
        public static string CantRevert {
            get {
                return ResourceManager.GetString("CantRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category added successfully.
        /// </summary>
        public static string CategoryAdded {
            get {
                return ResourceManager.GetString("CategoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category deleted successfully.
        /// </summary>
        public static string CategoryDeleted {
            get {
                return ResourceManager.GetString("CategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category edited successfully.
        /// </summary>
        public static string CategoryEdited {
            get {
                return ResourceManager.GetString("CategoryEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company added successfully.
        /// </summary>
        public static string CompanyAdded {
            get {
                return ResourceManager.GetString("CompanyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once deleted, you will not be able to recover this item.
        /// </summary>
        public static string DeleteMsg {
            get {
                return ResourceManager.GetString("DeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an empty required field.
        /// </summary>
        public static string EmptyVailds {
            get {
                return ResourceManager.GetString("EmptyVailds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group added successfully.
        /// </summary>
        public static string GroupAdded {
            get {
                return ResourceManager.GetString("GroupAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group deleted successfully.
        /// </summary>
        public static string GroupDeleted {
            get {
                return ResourceManager.GetString("GroupDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group edited successfully.
        /// </summary>
        public static string GroupEdited {
            get {
                return ResourceManager.GetString("GroupEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson added  successfully.
        /// </summary>
        public static string LessonAdded {
            get {
                return ResourceManager.GetString("LessonAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson deleted  successfully.
        /// </summary>
        public static string LessonDeleted {
            get {
                return ResourceManager.GetString("LessonDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson edited  successfully.
        /// </summary>
        public static string LessonEdited {
            get {
                return ResourceManager.GetString("LessonEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, cancel!.
        /// </summary>
        public static string NoCancel {
            get {
                return ResourceManager.GetString("NoCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no categories in the system.
        /// </summary>
        public static string NoCategory {
            get {
                return ResourceManager.GetString("NoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no companies in the system.
        /// </summary>
        public static string NoCompany {
            get {
                return ResourceManager.GetString("NoCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Country in the system.
        /// </summary>
        public static string NoCountry {
            get {
                return ResourceManager.GetString("NoCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no group in the system.
        /// </summary>
        public static string NoGroup {
            get {
                return ResourceManager.GetString("NoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lesson  successfully.
        /// </summary>
        public static string NoLesson {
            get {
                return ResourceManager.GetString("NoLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no companies type in the system.
        /// </summary>
        public static string NoType {
            get {
                return ResourceManager.GetString("NoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no users in the system.
        /// </summary>
        public static string NoUser {
            get {
                return ResourceManager.GetString("NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete it!.
        /// </summary>
        public static string YesDelete {
            get {
                return ResourceManager.GetString("YesDelete", resourceCulture);
            }
        }
    }
}
