//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Garages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Garages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legarage.Views.Garages.App_LocalResources.Garages", typeof(Garages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Model.
        /// </summary>
        public static string BrandModel {
            get {
                return ResourceManager.GetString("BrandModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string Bus {
            get {
                return ResourceManager.GetString("Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Address.
        /// </summary>
        public static string CityAddress {
            get {
                return ResourceManager.GetString("CityAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityArea.
        /// </summary>
        public static string CityArea {
            get {
                return ResourceManager.GetString("CityArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Address.
        /// </summary>
        public static string countryAdress {
            get {
                return ResourceManager.GetString("countryAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrption.
        /// </summary>
        public static string Descrption {
            get {
                return ResourceManager.GetString("Descrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desecription.
        /// </summary>
        public static string Desecription {
            get {
                return ResourceManager.GetString("Desecription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage Details.
        /// </summary>
        public static string DetailsPageTitle {
            get {
                return ResourceManager.GetString("DetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycle.
        /// </summary>
        public static string Motorcycle {
            get {
                return ResourceManager.GetString("Motorcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garages.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating of.
        /// </summary>
        public static string Ratingof {
            get {
                return ResourceManager.GetString("Ratingof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Brand.
        /// </summary>
        public static string SelectBrand {
            get {
                return ResourceManager.GetString("SelectBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Model.
        /// </summary>
        public static string SelectModel {
            get {
                return ResourceManager.GetString("SelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Rating.
        /// </summary>
        public static string SelectRating {
            get {
                return ResourceManager.GetString("SelectRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Service.
        /// </summary>
        public static string SelectService {
            get {
                return ResourceManager.GetString("SelectService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type.
        /// </summary>
        public static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to str.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck.
        /// </summary>
        public static string Truck {
            get {
                return ResourceManager.GetString("Truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VehicleSizes.
        /// </summary>
        public static string VehicleSizes {
            get {
                return ResourceManager.GetString("VehicleSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Types.
        /// </summary>
        public static string VehicleTypes {
            get {
                return ResourceManager.GetString("VehicleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
