//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CP_RentOffices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CP_RentOffices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legarage.Views.CP_RentOffices.App_LocalResources.CP_RentOffices", typeof(CP_RentOffices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new rent office.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rent office has been added.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new image.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose the country firstly.
        /// </summary>
        public static string ChoseCountryFirstly {
            get {
                return ResourceManager.GetString("ChoseCountryFirstly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently image.
        /// </summary>
        public static string Currentlyimage {
            get {
                return ResourceManager.GetString("Currentlyimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the rent office.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reent office has been deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the image.
        /// </summary>
        public static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The descrption.
        /// </summary>
        public static string Descrption {
            get {
                return ResourceManager.GetString("Descrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rent office details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the rent office.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rent office has been edited.
        /// </summary>
        public static string Edited {
            get {
                return ResourceManager.GetString("Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an image to change the current image.
        /// </summary>
        public static string EditImage {
            get {
                return ResourceManager.GetString("EditImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address.
        /// </summary>
        public static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterAddressPlease.
        /// </summary>
        public static string EnterAddressPlease {
            get {
                return ResourceManager.GetString("EnterAddressPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterCityPlease.
        /// </summary>
        public static string EnterCityPlease {
            get {
                return ResourceManager.GetString("EnterCityPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the descrption.
        /// </summary>
        public static string EnterDescrption {
            get {
                return ResourceManager.GetString("EnterDescrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the descrption please.
        /// </summary>
        public static string EnterDescrptionPlease {
            get {
                return ResourceManager.GetString("EnterDescrptionPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the facebook.
        /// </summary>
        public static string EnterFacebook {
            get {
                return ResourceManager.GetString("EnterFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the fax.
        /// </summary>
        public static string EnterFax {
            get {
                return ResourceManager.GetString("EnterFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image of the rent office.
        /// </summary>
        public static string EnterImage {
            get {
                return ResourceManager.GetString("EnterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the image please.
        /// </summary>
        public static string EnterImagePlease {
            get {
                return ResourceManager.GetString("EnterImagePlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the instagram.
        /// </summary>
        public static string EnterInstagram {
            get {
                return ResourceManager.GetString("EnterInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the linkedin.
        /// </summary>
        public static string EnterLinkedin {
            get {
                return ResourceManager.GetString("EnterLinkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the models please.
        /// </summary>
        public static string EnterModelPlease {
            get {
                return ResourceManager.GetString("EnterModelPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the rent office name.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the rent office name please.
        /// </summary>
        public static string EnterNamePlease {
            get {
                return ResourceManager.GetString("EnterNamePlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the owner name.
        /// </summary>
        public static string EnterOwnerName {
            get {
                return ResourceManager.GetString("EnterOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the owner name please.
        /// </summary>
        public static string EnterOwnerNamePlease {
            get {
                return ResourceManager.GetString("EnterOwnerNamePlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phonenumber please.
        /// </summary>
        public static string EnterPhonePlease {
            get {
                return ResourceManager.GetString("EnterPhonePlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the snapchat.
        /// </summary>
        public static string EnterSnapchat {
            get {
                return ResourceManager.GetString("EnterSnapchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the tiktok.
        /// </summary>
        public static string EnterTiktok {
            get {
                return ResourceManager.GetString("EnterTiktok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the twitter.
        /// </summary>
        public static string EnterTwitter {
            get {
                return ResourceManager.GetString("EnterTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the vehicle types please.
        /// </summary>
        public static string EnterVehiclePlease {
            get {
                return ResourceManager.GetString("EnterVehiclePlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the website.
        /// </summary>
        public static string EnterWebsite {
            get {
                return ResourceManager.GetString("EnterWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the WhatsApp number please.
        /// </summary>
        public static string EnterWhatsappPlease {
            get {
                return ResourceManager.GetString("EnterWhatsappPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the youtube.
        /// </summary>
        public static string EnterYoutube {
            get {
                return ResourceManager.GetString("EnterYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instagram.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linkedin.
        /// </summary>
        public static string Linkedin {
            get {
                return ResourceManager.GetString("Linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The models.
        /// </summary>
        public static string Models {
            get {
                return ResourceManager.GetString("Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of rent office.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The is no brands avalible.
        /// </summary>
        public static string NoBrand {
            get {
                return ResourceManager.GetString("NoBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no city avalibe.
        /// </summary>
        public static string NoCity {
            get {
                return ResourceManager.GetString("NoCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no country avalible.
        /// </summary>
        public static string NoCountry {
            get {
                return ResourceManager.GetString("NoCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no images avalible.
        /// </summary>
        public static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no models avalible.
        /// </summary>
        public static string NoModel {
            get {
                return ResourceManager.GetString("NoModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no rent offices avalible.
        /// </summary>
        public static string NoRentOffices {
            get {
                return ResourceManager.GetString("NoRentOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no vehicles avalible.
        /// </summary>
        public static string NoVehicle {
            get {
                return ResourceManager.GetString("NoVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner name.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rent offices.
        /// </summary>
        public static string RentOffices {
            get {
                return ResourceManager.GetString("RentOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snapchat.
        /// </summary>
        public static string Snapchat {
            get {
                return ResourceManager.GetString("Snapchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tiktok.
        /// </summary>
        public static string Tiktok {
            get {
                return ResourceManager.GetString("Tiktok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Vehicles.
        /// </summary>
        public static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Whatsapp number.
        /// </summary>
        public static string Whatsapp {
            get {
                return ResourceManager.GetString("Whatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The youtube.
        /// </summary>
        public static string Youtube {
            get {
                return ResourceManager.GetString("Youtube", resourceCulture);
            }
        }
    }
}
