//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CP_Winches {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CP_Winches() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("legarage.Views.CP_Winches.App_LocalResources.CP_Winches", typeof(CP_Winches).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new winche.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The winche has been added.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The winche image has been added.
        /// </summary>
        public static string AddedImage {
            get {
                return ResourceManager.GetString("AddedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new image.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the winche image please.
        /// </summary>
        public static string AddImageP {
            get {
                return ResourceManager.GetString("AddImageP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose the country firstliy.
        /// </summary>
        public static string ChoseCountryFirstiy {
            get {
                return ResourceManager.GetString("ChoseCountryFirstiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the winche.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The winche has been deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The winche image has been deleted.
        /// </summary>
        public static string DeletedImage {
            get {
                return ResourceManager.GetString("DeletedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the image.
        /// </summary>
        public static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The descrption.
        /// </summary>
        public static string Descrption {
            get {
                return ResourceManager.GetString("Descrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The winche details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The driver name.
        /// </summary>
        public static string DriverName {
            get {
                return ResourceManager.GetString("DriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The driver phone.
        /// </summary>
        public static string DriverPhone {
            get {
                return ResourceManager.GetString("DriverPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the winche.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The winche has been edited.
        /// </summary>
        public static string Edited {
            get {
                return ResourceManager.GetString("Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Image to change the current image.
        /// </summary>
        public static string EditImage {
            get {
                return ResourceManager.GetString("EditImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address.
        /// </summary>
        public static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address please.
        /// </summary>
        public static string EnterAddressP {
            get {
                return ResourceManager.GetString("EnterAddressP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the area.
        /// </summary>
        public static string EnterArea {
            get {
                return ResourceManager.GetString("EnterArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the city please.
        /// </summary>
        public static string EnterCityP {
            get {
                return ResourceManager.GetString("EnterCityP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the descrption.
        /// </summary>
        public static string EnterDescrption {
            get {
                return ResourceManager.GetString("EnterDescrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the descrption please.
        /// </summary>
        public static string EnterDescrptionP {
            get {
                return ResourceManager.GetString("EnterDescrptionP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the driver name.
        /// </summary>
        public static string EnterDriverName {
            get {
                return ResourceManager.GetString("EnterDriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the driver name please.
        /// </summary>
        public static string EnterDriverNameP {
            get {
                return ResourceManager.GetString("EnterDriverNameP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the driver phone.
        /// </summary>
        public static string EnterDriverPhone {
            get {
                return ResourceManager.GetString("EnterDriverPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the driver phone number please.
        /// </summary>
        public static string EnterDriverPhoneP {
            get {
                return ResourceManager.GetString("EnterDriverPhoneP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the keywords.
        /// </summary>
        public static string EnterKeywords {
            get {
                return ResourceManager.GetString("EnterKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the keywords please.
        /// </summary>
        public static string EnterKeywordsP {
            get {
                return ResourceManager.GetString("EnterKeywordsP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the owner name.
        /// </summary>
        public static string EnterOwnerName {
            get {
                return ResourceManager.GetString("EnterOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phone please.
        /// </summary>
        public static string EnterPhoneP {
            get {
                return ResourceManager.GetString("EnterPhoneP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title.
        /// </summary>
        public static string EnterTitle {
            get {
                return ResourceManager.GetString("EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title please.
        /// </summary>
        public static string EnterTitleP {
            get {
                return ResourceManager.GetString("EnterTitleP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the owner name.
        /// </summary>
        public static string EnterUserP {
            get {
                return ResourceManager.GetString("EnterUserP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the vehicle sizes.
        /// </summary>
        public static string EnterVehicleSizes {
            get {
                return ResourceManager.GetString("EnterVehicleSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the vehicle sizes please.
        /// </summary>
        public static string EnterVehicleSizesP {
            get {
                return ResourceManager.GetString("EnterVehicleSizesP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Whatsapp number please.
        /// </summary>
        public static string EnterWhatsappP {
            get {
                return ResourceManager.GetString("EnterWhatsappP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The winche image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The winche images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no city.
        /// </summary>
        public static string NoCity {
            get {
                return ResourceManager.GetString("NoCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no country.
        /// </summary>
        public static string NoCountry {
            get {
                return ResourceManager.GetString("NoCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no images avalible.
        /// </summary>
        public static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no users avalible.
        /// </summary>
        public static string NoUser {
            get {
                return ResourceManager.GetString("NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no winches avalible.
        /// </summary>
        public static string NoWinches {
            get {
                return ResourceManager.GetString("NoWinches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The driver name.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle sizes.
        /// </summary>
        public static string VehicleSizes {
            get {
                return ResourceManager.GetString("VehicleSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Whatsapp number.
        /// </summary>
        public static string Whatsapp {
            get {
                return ResourceManager.GetString("Whatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The winches.
        /// </summary>
        public static string Winches {
            get {
                return ResourceManager.GetString("Winches", resourceCulture);
            }
        }
    }
}
